### ISSUE TITLE
Would Meower Mobile support Android 4.4+?

### ISSUE THREAD

**Issue by Mwalters75** [meower-media-co/MeowerMobile#1]

**Comment by tnix100** [comment]
I will test it out on Android 4.4 soon and get back to you once my testing has concluded!

**Comment by Mwalters75** [comment]
Thanks!

**Comment by tnix100** [comment]
We have made a spreadsheet on what versions of Android will be supported, once we test 4.4 we'll add it to there.

https://docs.google.com/spreadsheets/d/1otJu5ldjapSFbOvq3QAWSwFpRmQuhj6y/edit#gid=1175350865
