### ISSUE TITLE
[11.x] Incorrect login causes graphical glitch

### ISSUE THREAD

**Issue by Melt2002** [meower-media-co/MeowerMobile#2]
When I log in with the wrong password, the home page appears, half off screen for about half a second before giving me the login error and returning me to the log in screen.

**Comment by tnix100** [comment]
Are you able to reproduce this and send a video or screen recording of it happening?

**Comment by JoshAtticus** [comment]
I don't get this glitch on my Android 11 device, except that the login button is so squashed it doesn't have any text in it

**Comment by Melt2002** [comment]
This fixed itself in the 0.4 release somehow.
