### ISSUE TITLE
[11.x] Incorrect profile picture

### ISSUE THREAD

**Issue by Melt2002** [meower-media-co/MeowerMobile#5]
My profile picture is Scratch Cat, but the mobile app shows Gobo.

**Comment by tnix100** [comment]
Thanks for reporting this! I found this bug while using the app too, it will be fixed in the next update :)

**Comment by JoshAtticus** [comment]
This issue still exists

**Comment by Melt2002** [comment]
It will be fixed in the next update, as @tnix100 said.
